### ISSUE TITLE
iOS app is not working with iOS 16.4

### ISSUE THREAD

**Issue by rajivnw** [webdriverio/native-demo-app#130]
iOS demo app open and then close immediately. Even when try installing manually unable to access the app.

Some Appium logs:

[debug] [XCUITest] Checking whether app '/var/folders/_b/zs7rq91d2zz38h82t_0_0zqh0000gn/T/2023728-6795-1w98jul.1khz/wdioNativeDemoApp.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [XCUITest] Getting bundle ID from app '/var/folders/_b/zs7rq91d2zz38h82t_0_0zqh0000gn/T/2023728-6795-1w98jul.1khz/wdioNativeDemoApp.app': 'org.wdioNativeDemoApp'
[debug] [XCUITestDriver@89a9 (d503622c)] Event 'resetStarted' logged at 1693197484497 (00:38:04 GMT-0400 (Eastern Daylight Time))
[debug] [simctl] Error running 'terminate': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Simulator device returned an error for the requested operation.
found nothing to terminate
Underlying error (domain=NSPOSIXErrorDomain, code=3):
	The operation couldn’t be completed. found nothing to terminate
	found nothing to terminate
[XCUITest] Reset: failed to terminate Simulator application with id "org.wdioNativeDemoApp"
[XCUITest] Not scrubbing third party app in anticipation of uninstall

**Comment by christian-bromann** [comment]
Hey @rajivnw 👋 thanks for raising the issue.

Unfortunately no contributor had time to update the app we are using here which is why it is not working in the latest iOS environment. Any help in updating the app would be much appreciated.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by wswebcreation** [comment]
This will be fixed with our new release in a few days
